entities:
  # Removal times for entities can be configured here, in ticks.
  # Values below 0 will have no effect (disabled).
  # The default 2400 ticks will make these entities disappear after 2 minutes.
  snowball: 2400
  llama_spit: 2400
  egg: 2400
  ender_pearl: 2400
  wither_skull: 2400
  potion: 2400
  experience_bottle: 2400
